'use client';

import { useActionState, useEffect, useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import {
  createPromoCodeAction,
  deletePromoCodeAction,
  updatePromoCodeAction,
  type PromoCodeActionState,
} from '@/tickets-portal/actions/promo-codes';
import type { AdminPromoCode } from '@/tickets-portal/types/admin-promo-codes';
import { formatMinorToNgn } from '@/tickets-portal/lib/format-money';

const fieldClass =
  'w-full rounded-md border border-stone-200 bg-white px-3 py-2.5 text-[15px] text-stone-900 outline-none focus:border-stone-300 focus:ring-2 focus:ring-stone-900/10';
const labelClass = 'mb-1.5 block text-[13px] font-medium text-stone-700';

function ActionError({ state }: { state: PromoCodeActionState }) {
  if (!state?.error) return null;
  return (
    <p className="rounded-md border border-red-200 bg-red-50/90 px-3 py-2 text-[13px] text-red-900">
      {state.error}
    </p>
  );
}

export function PromoCodesManager({
  codes,
  events,
  ownerKind,
  ownerId,
}: {
  codes: AdminPromoCode[];
  events: Array<{ id: string; name: string }>;
  ownerKind: 'influencer' | 'community';
  ownerId: string;
}) {
  const router = useRouter();
  const [isPendingDelete, startDeleteTransition] = useTransition();
  const [editingId, setEditingId] = useState<string | null>(null);
  const [createKey, setCreateKey] = useState(0);

  const eventNameById = useMemo(
    () => new Map(events.map((e) => [e.id, e.name])),
    [events],
  );

  const editing = editingId ? codes.find((c) => c._id === editingId) : undefined;

  const [createState, createAction] = useActionState(createPromoCodeAction, undefined);
  const [updateState, updateAction] = useActionState(updatePromoCodeAction, undefined);

  useEffect(() => {
    if (createState?.ok) {
      setCreateKey((k) => k + 1);
      router.refresh();
    }
  }, [createState?.ok, router]);

  useEffect(() => {
    if (updateState?.ok) {
      setEditingId(null);
      router.refresh();
    }
  }, [updateState?.ok, router]);

  const tableWrap =
    'overflow-x-auto overflow-hidden rounded-lg border border-stone-200/90 bg-white shadow-[0_1px_2px_rgba(0,0,0,0.04)]';
  const th = 'px-4 py-3 text-left text-[12px] font-medium text-stone-400';
  const td = 'px-4 py-3 text-[14px] text-stone-700';

  const scopeLabel = (p: AdminPromoCode) =>
    p.eventId ? eventNameById.get(p.eventId) ?? p.eventId.slice(-8) : 'Global';

  const discountLabel = (p: AdminPromoCode) =>
    p.discountType === 'percentage'
      ? `${p.discountValue}%`
      : formatMinorToNgn(p.discountValue);

  const ownerHidden =
    ownerKind === 'influencer' ? (
      <input type="hidden" name="influencerId" value={ownerId} />
    ) : (
      <input type="hidden" name="communityId" value={ownerId} />
    );

  const title =
    ownerKind === 'influencer'
      ? 'Promo codes for this influencer'
      : 'Promo codes for this community';

  return (
    <div className="space-y-10">
      <section className="space-y-4">
        <h2 className="text-[15px] font-semibold text-stone-900">Create promo code</h2>
        <p className="text-[13px] text-stone-600">{title} — each code links to this record by id.</p>
        <ActionError state={createState} />
        <form key={createKey} action={createAction} className="space-y-4 rounded-lg border border-stone-200 bg-white p-5 shadow-sm">
          <input type="hidden" name="ownerKind" value={ownerKind} />
          <input type="hidden" name="ownerId" value={ownerId} />
          {ownerHidden}

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className={labelClass} htmlFor="create-code">
                Code (customer-entered)
              </label>
              <input id="create-code" name="code" required className={fieldClass} placeholder="SAVE20" />
            </div>
            <div>
              <p className={labelClass}>Tracking ref</p>
              <p className="rounded-md border border-dashed border-stone-200 bg-stone-50 px-3 py-2.5 text-[14px] text-stone-500">
                Auto-generated by the API when you create the code.
              </p>
            </div>
          </div>

          {ownerKind === 'influencer' ? (
            <div>
              <label className={labelClass} htmlFor="create-discountType-inf">
                Discount type
              </label>
              <select id="create-discountType-inf" name="discountType" required className={fieldClass}>
                <option value="percentage">Percentage</option>
                <option value="fixed">Fixed (minor units)</option>
              </select>
            </div>
          ) : (
            <>
              <input type="hidden" name="discountType" value="fixed" />
              <p className="text-[13px] text-stone-600">
                Community promos use a <span className="font-medium">fixed</span> discount in minor units (same unit as
                tier prices).
              </p>
            </>
          )}

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className={labelClass} htmlFor="create-discountValue">
                Discount value
              </label>
              <input
                id="create-discountValue"
                name="discountValue"
                type="number"
                min={0}
                step={1}
                required
                className={fieldClass}
              />
              <p className="mt-1 text-[12px] text-stone-500">
                Percentage 0–100, or fixed amount in minor units (e.g. kobo).
              </p>
            </div>
            <div>
              <label className={labelClass} htmlFor="create-maxUses">
                Max uses (optional)
              </label>
              <input id="create-maxUses" name="maxUses" type="number" min={0} step={1} className={fieldClass} />
            </div>
          </div>

          <div>
            <label className={labelClass} htmlFor="create-eventId">
              Event scope
            </label>
            <select id="create-eventId" name="eventId" className={fieldClass} defaultValue="">
              <option value="">Global — all events</option>
              {events.map((e) => (
                <option key={e.id} value={e.id}>
                  {e.name}
                </option>
              ))}
            </select>
          </div>

          <label className="flex items-center gap-2 text-[14px] text-stone-700">
            <input type="checkbox" name="isActive" defaultChecked className="rounded border-stone-300" />
            Active
          </label>

          <button
            type="submit"
            className="rounded-md bg-stone-900 px-4 py-2.5 text-[14px] font-medium text-white hover:bg-stone-800"
          >
            Create code
          </button>
        </form>
      </section>

      {editing ? (
        <section className="space-y-4 rounded-lg border border-stone-300 bg-stone-50/80 p-5">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <h2 className="text-[15px] font-semibold text-stone-900">Edit {editing.code}</h2>
            <button
              type="button"
              onClick={() => setEditingId(null)}
              className="text-[13px] font-medium text-stone-600 hover:text-stone-900"
            >
              Cancel
            </button>
          </div>
          <ActionError state={updateState} />
          <form key={editing._id} action={updateAction} className="space-y-4">
            <input type="hidden" name="ownerKind" value={ownerKind} />
            <input type="hidden" name="ownerId" value={ownerId} />
            {ownerHidden}
            <input type="hidden" name="promoId" value={editing._id} />

            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className={labelClass}>Code</label>
                <input name="code" required defaultValue={editing.code} className={fieldClass} />
              </div>
              <div>
                <p className={labelClass}>Tracking ref</p>
                <p className="rounded-md border border-dashed border-stone-200 bg-white px-3 py-2.5 font-mono text-[14px] text-stone-700">
                  {editing.trackingRef}
                </p>
              </div>
            </div>

            {ownerKind === 'community' ? (
              <input type="hidden" name="discountType" value="fixed" />
            ) : (
              <div>
                <label className={labelClass}>Discount type</label>
                <select name="discountType" required className={fieldClass} defaultValue={editing.discountType}>
                  <option value="percentage">Percentage</option>
                  <option value="fixed">Fixed (minor units)</option>
                </select>
              </div>
            )}

            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className={labelClass}>Discount value</label>
                <input
                  name="discountValue"
                  type="number"
                  min={0}
                  step={1}
                  required
                  defaultValue={editing.discountValue}
                  className={fieldClass}
                />
              </div>
              <div>
                <label className={labelClass}>Max uses</label>
                <input
                  name="maxUses"
                  type="number"
                  min={0}
                  step={1}
                  defaultValue={editing.maxUses ?? ''}
                  className={fieldClass}
                  placeholder="Leave blank to keep unchanged"
                />
              </div>
            </div>

            <div>
              <label className={labelClass}>Event scope</label>
              <select name="eventId" className={fieldClass} defaultValue={editing.eventId ?? ''}>
                <option value="">Global — all events</option>
                {events.map((e) => (
                  <option key={e.id} value={e.id}>
                    {e.name}
                  </option>
                ))}
              </select>
            </div>

            <label className="flex items-center gap-2 text-[14px] text-stone-700">
              <input type="checkbox" name="isActive" defaultChecked={editing.isActive} className="rounded border-stone-300" />
              Active
            </label>

            <button
              type="submit"
              className="rounded-md bg-stone-900 px-4 py-2.5 text-[14px] font-medium text-white hover:bg-stone-800"
            >
              Save changes
            </button>
          </form>
        </section>
      ) : null}

      <section className={tableWrap}>
        <table className="w-full min-w-[640px]">
          <thead>
            <tr className="border-b border-stone-100">
              <th className={th}>Code</th>
              <th className={th}>Discount</th>
              <th className={`${th} hidden md:table-cell`}>Tracking</th>
              <th className={`${th} hidden lg:table-cell`}>Scope</th>
              <th className={th}>Uses</th>
              <th className={th}>Active</th>
              <th className={`${th} text-right`}>
                <span className="sr-only">Actions</span>
              </th>
            </tr>
          </thead>
          <tbody>
            {codes.length === 0 ? (
              <tr>
                <td colSpan={7} className={`${td} py-14 text-center text-stone-400`}>
                  No promo codes yet.
                </td>
              </tr>
            ) : (
              codes.map((p) => (
                <tr key={p._id} className="border-b border-stone-100 last:border-0">
                  <td className={`${td} font-mono text-[13px] font-medium text-stone-900`}>{p.code}</td>
                  <td className={td}>{discountLabel(p)}</td>
                  <td className={`${td} hidden font-mono text-[13px] text-stone-600 md:table-cell`}>
                    {p.trackingRef}
                  </td>
                  <td className={`${td} hidden max-w-[140px] truncate text-[13px] lg:table-cell`}>
                    {scopeLabel(p)}
                  </td>
                  <td className={`${td} tabular-nums text-[13px]`}>
                    {p.usageCount}
                    {p.maxUses != null ? ` / ${p.maxUses}` : ''}
                  </td>
                  <td className={td}>{p.isActive ? 'Yes' : 'No'}</td>
                  <td className={`${td} whitespace-nowrap text-right`}>
                    <button
                      type="button"
                      onClick={() => setEditingId(p._id)}
                      className="mr-3 text-[13px] font-medium text-stone-800 underline-offset-4 hover:underline"
                    >
                      Edit
                    </button>
                    <button
                      type="button"
                      disabled={isPendingDelete}
                      className="text-[13px] font-medium text-red-800 underline-offset-4 hover:underline disabled:opacity-50"
                      onClick={() => {
                        if (!window.confirm(`Deactivate promo "${p.code}"?`)) return;
                        const fd = new FormData();
                        fd.set('promoId', p._id);
                        fd.set('ownerKind', ownerKind);
                        fd.set('ownerId', ownerId);
                        startDeleteTransition(async () => {
                          const r = await deletePromoCodeAction(undefined, fd);
                          if (r?.error) {
                            window.alert(r.error);
                            return;
                          }
                          router.refresh();
                        });
                      }}
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </section>
    </div>
  );
}
